-- Seed some popular games
INSERT INTO game_catalog (bgg_id, title, year_published, min_players, max_players, playing_time, age, description, image, publisher, categories, rating, complexity)
VALUES
(13, 'Catan', 1995, 3, 4, 120, 10, 'In Catan (formerly The Settlers of Catan), players try to be the dominant force on the island of Catan by building settlements, cities, and roads.', 'https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__original/img/8a9HeqFfsMtDFnzaMivCsJPveG4=/0x0/filters:format(jpeg)/pic2419375.jpg', 'KOSMOS', ARRAY['Strategy', 'Family'], 7.1, 2.3),
(822, 'Carcassonne', 2000, 2, 5, 45, 7, 'Carcassonne is a tile-placement game in which the players draw and place a tile with a piece of southern French landscape on it.', 'https://cf.geekdo-images.com/okM0dq_bEXnbyQTOvHrwXA__original/img/hP6V5s0s9L5tX6I8fJ5v8Z1qZ1Q=/0x0/filters:format(jpeg)/pic6544250.jpg', 'Hans im Glück', ARRAY['Family', 'Medieval'], 7.4, 1.9),
(9209, 'Ticket to Ride', 2004, 2, 5, 60, 8, 'Ticket to Ride is a cross-country train adventure in which players collect and play matching train cards to claim railway routes connecting cities throughout North America.', 'https://cf.geekdo-images.com/ZWJg0dCdrWHxVnc0eFq3qQ__original/img/Z8g6g7g8g9g0g1g2g3g4g5g6g7=/0x0/filters:format(jpeg)/pic3866314.jpg', 'Days of Wonder', ARRAY['Family', 'Trains'], 7.4, 1.8),
(30549, 'Pandemic', 2008, 2, 4, 45, 8, 'In Pandemic, several virulent diseases have broken out simultaneously all over the world! The players are disease-fighting specialists whose mission is to treat disease hotspots while researching cures.', 'https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXLLjVqA__original/img/Is-8L8L8L8L8L8L8L8L8L8L8L8=/0x0/filters:format(jpeg)/pic1534148.jpg', 'Z-Man Games', ARRAY['Strategy', 'Cooperative'], 7.6, 2.4),
(167791, 'Terraforming Mars', 2016, 1, 5, 120, 12, 'In the 2400s, mankind begins to terraform the planet Mars. Giant corporations, sponsored by the World Government on Earth, initiate huge projects to raise the temperature, the oxygen level, and the ocean coverage until the environment is habitable.', 'https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__original/img/bt4o6o8o0o2o4o6o8o0o2o4o6=/0x0/filters:format(jpeg)/pic3536616.jpg', 'FryxGames', ARRAY['Strategy', 'Sci-Fi'], 8.4, 3.2),
(174430, 'Gloomhaven', 2017, 1, 4, 120, 14, 'Gloomhaven is a game of Euro-inspired tactical combat in a persistent world of shifting motives. Players will take on the role of a wandering adventurer with their own special set of skills and their own reasons for traveling to this dark corner of the world.', 'https://cf.geekdo-images.com/sZYp_3BTDGjh2unaZfZmuA__original/img/7d-8d9d0d1d2d3d4d5d6d7d8d9=/0x0/filters:format(jpeg)/pic2437871.jpg', 'Cephalofair Games', ARRAY['Strategy', 'Fantasy'], 8.7, 3.8),
(266192, 'Wingspan', 2019, 1, 5, 70, 10, 'Wingspan is a competitive, medium-weight, card-driven, engine-building board game from Stonemaier Games. You are bird enthusiasts—researchers, bird watchers, ornithologists, and collectors—seeking to discover and attract the best birds to your network of wildlife preserves.', 'https://cf.geekdo-images.com/yLZJCVLlIx4c7eJEWUNJ7w__original/img/c6c7c8c9c0c1c2c3c4c5c6c7c8=/0x0/filters:format(jpeg)/pic4458123.jpg', 'Stonemaier Games', ARRAY['Strategy', 'Animals'], 8.1, 2.4),
(230802, 'Azul', 2017, 2, 4, 45, 8, 'Azul was designed by the world famous, award-winning game author Michael Kiesling. Azul captures the beautiful aesthetics of Moorish art in a contemporary board game.', 'https://cf.geekdo-images.com/tz19Cv8O9hHk8Z8Z8Z8Z8Z__original/img/8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8Z8=/0x0/filters:format(jpeg)/pic3718275.jpg', 'Plan B Games', ARRAY['Family', 'Abstract'], 7.8, 1.8),
(173346, '7 Wonders Duel', 2015, 2, 2, 30, 10, 'In many ways 7 Wonders Duel resembles its parent game 7 Wonders as over three ages players acquire cards that provide resources or advance their military or scientific development in order to develop a civilization and complete wonders.', 'https://cf.geekdo-images.com/WzBsga_uLP9kO91gZ7H8yw__original/img/8a9HeqFfsMtDFnzaMivCsJPveG4=/0x0/filters:format(jpeg)/pic2576399.jpg', 'Repos Production', ARRAY['Strategy', 'Card Game'], 8.1, 2.2),
(36218, 'Dominion', 2008, 2, 4, 30, 13, 'You are a monarch, like your parents before you, a ruler of a small pleasant kingdom of rivers and evergreens. Unlike your parents, however, you have hopes and dreams! You want a bigger and more pleasant kingdom, with more rivers and a wider variety of trees.', 'https://cf.geekdo-images.com/j6iQpZ4Xp9Xp0Xp1Xp2Xp3Xp4=/0x0/filters:format(jpeg)/pic394356.jpg', 'Rio Grande Games', ARRAY['Strategy', 'Card Game'], 7.6, 2.3)
ON CONFLICT (bgg_id) DO NOTHING;
