"use client"

import { useState } from "react"
import Link from "next/link"
import { Navigation } from "@/components/navigation"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { ArrowLeft, RefreshCw, Trash2, Maximize2, X } from "lucide-react"
import { MessageSquareText } from "lucide-react"
import { motion, AnimatePresence } from "framer-motion"

const wordCategories: Record<string, string[]> = {
  tiere: [
    "Aal",
    "Adler",
    "Elefant",
    "Albatros",
    "Alpaka",
    "Ameise",
    "Ameisenbär",
    "Amsel",
    "Anglerfisch",
    "Antilope",
    "Assel",
    "Auster",
    "Bär",
    "Barrakuda",
    "Barsch",
    "Beluga",
    "Biber",
    "Biene",
    "Bison",
    "Blauwal",
    "Blaumeise",
    "Blutegel",
    "Bonobo",
    "Büffel",
    "Bussard",
    "Chamäleon",
    "Dachs",
    "Delfin",
    "Dingo",
    "Dohle",
    "Dorsch",
    "Dromedar",
    "Echse",
    "Eichhörnchen",
    "Eisbär",
    "Eisvogel",
    "Elch",
    "Elster",
    "Emu",
    "Ente",
    "Erdkröte",
    "Erdmännchen",
    "Esel",
    "Eselspinguin",
    "Eule",
    "Falke",
    "Falken",
    "Fasan",
    "Faultier",
    "Ferkel",
    "Fischreiher",
    "Flamingo",
    "Fledermaus",
    "Flughörnchen",
    "Forelle",
    "Fohlen",
    "Frosch",
    "Fuchs",
    "Gämse",
    "Gans",
    "Gazelle",
    "Gepard",
    "Gecko",
    "Geier",
    "Gibbon",
    "Giraffe",
    "Goldfisch",
    "Gorilla",
    "Grashüpfer",
    "Gnu",
    "Gürteltier",
    "Habicht",
    "Hahn",
    "Hammerhai",
    "Hamster",
    "Hase",
    "Hecht",
    "Hering",
    "Hirsch",
    "Hirschkäfer",
    "Hornisse",
    "Huhn",
    "Hund",
    "Hummel",
    "Igel",
    "Jaguar",
    "Kakadu",
    "Kalb",
    "Kamel",
    "Kanarienvogel",
    "Karpfen",
    "Karpfenfisch",
    "Katzenhai",
    "Katze",
    "Känguru",
    "Kiwi",
    "Kolibri",
    "Kojote",
    "Koala",
    "Kormoran",
    "Kobra",
    "Krabbe",
    "Krake",
    "Kranich",
    "Krebs",
    "Kreuzspinne",
    "Krokodil",
    "Küken",
    "Kuckuck",
    "Lama",
    "Lachs",
    "Landschildkröte",
    "Laus",
    "Leguan",
    "Lemur",
    "Libelle",
    "Luchs",
    "Lurch",
    "Mammut",
    "Mandrill",
    "Marienkäfer",
    "Marder",
    "Marderhund",
    "Maus",
    "Meerschweinchen",
    "Meerkatze",
    "Meise",
    "Molch",
    "Möwe",
    "Muräne",
    "Mufflon",
    "Moschusochse",
    "Motte",
    "Nacktschnecke",
    "Nasenaffe",
    "Narwal",
    "Nashorn",
    "Nilpferd",
    "Okapi",
    "Oktopus",
    "Opossum",
    "Orang-Utan",
    "Orca",
    "Ozelot",
    "Panda",
    "Pavian",
    "Papagei",
    "Papageientaucher",
    "Pelikan",
    "Pfau",
    "Pinguin",
    "Polarhase",
    "Polarwolf",
    "Python",
    "Qualle",
    "Rabe",
    "Rauhaardackel",
    "Raupe",
    "Rebhuhn",
    "Regenwurm",
    "Reh",
    "Rentier",
    "Riesenschildkröte",
    "Rochen",
    "Roter Panda",
    "Rotfuchs",
    "Rotkehlchen",
    "Salamander",
    "Säbelzahntiger",
    "Sardine",
    "Schaf",
    "Schakal",
    "Schimpanse",
    "Schlange",
    "Schmetterling",
    "Schneeleopard",
    "Schnabeltier",
    "Schnake",
    "Schnecke",
    "Schneeeule",
    "Schwalbe",
    "Schwan",
    "Seeadler",
    "Seehund",
    "Seeigel",
    "Seelöwe",
    "Seepferdchen",
    "Seestern",
    "Seeotter",
    "Skorpion",
    "Spatz",
    "Specht",
    "Vogelspinne",
    "Springbock",
    "Steinbock",
    "Stinktier",
    "Storch",
    "Stör",
    "Strauß",
    "Tausendfüßler",
    "Taube",
    "Teichmolch",
    "Tiger",
    "Tintenfisch",
    "Totenkopfaffe",
    "Truthahn",
    "Tukan",
    "Uhu",
    "Viper",
    "Wachtel",
    "Walross",
    "Wanze",
    "Waran",
    "Wels",
    "Weinbergschnecke",
    "Weißkopfseeadler",
    "Wellensittich",
    "Wespe",
    "Wildschwein",
    "Wolf",
    "Wombat",
    "Yak",
    "Zebra",
    "Ziege",
    "Zitteraal",
    "Zitronenfalter",
    "Plankton",
  ],
  berufe: [
    "Abfallentsorger",
    "Apotheker",
    "Architekt",
    "Arzthelfer",
    "Arzt",
    "Augenoptiker",
    "Automechaniker",
    "Autoverkäufer",
    "Bäcker",
    "Banker",
    "Bauingenieur",
    "Bauleiter",
    "Bestatter",
    "Bildhauer",
    "Biologe",
    "Bodenleger",
    "Brauer",
    "Buchhalter",
    "Busfahrer",
    "Bürokaufmann",
    "Callcenter-Agent",
    "Chemiker",
    "Chirurg",
    "Choreograf",
    "Dachdecker",
    "Datenanalyst",
    "Dentalassistent",
    "Dolmetscher",
    "Drucker",
    "Elektriker",
    "Empfangsmitarbeiter",
    "Ergotherapeut",
    "Erzieher",
    "Eventmanager",
    "Fahrlehrer",
    "Feuerwehrmann",
    "Fensterbauer",
    "Fischer",
    "Flight Attendant",
    "Florist",
    "Forstwirt",
    "Fotograf",
    "Forscher",
    "Gastronom",
    "Gebäudereiniger",
    "Gebäudetechniker",
    "Gärtner",
    "Gerüstbauer",
    "Glasbläser",
    "Goldschmied",
    "Grafiker",
    "Großhandelskaufmann",
    "Hausmeister",
    "Hebamme",
    "Hotelmanager",
    "Imker",
    "Ingenieur",
    "Jäger",
    "Journalist",
    "Kapitän",
    "Kaufmann",
    "Kellner",
    "Kindergärtner",
    "Klempner",
    "Koch",
    "Kochgehilfe",
    "Konditor",
    "Kosmetikerin",
    "Künstler",
    "LKW-Fahrer",
    "Laborant",
    "Landwirt",
    "Lehrer",
    "Logistiker",
    "Logopäde",
    "Lokführer",
    "Makler",
    "Maler",
    "Marketingmanager",
    "Maurer",
    "Mechaniker",
    "Mediengestalter",
    "Medizinische Fachangestellte",
    "Metzger",
    "Montagearbeiter",
    "Musiker",
    "Museumspädagoge",
    "Netzwerktechniker",
    "Notar",
    "Office-Manager",
    "Orthopäde",
    "Personalmanager",
    "Pflegekraft",
    "Physiotherapeut",
    "Pilot",
    "Polizist",
    "Postbote",
    "Professor",
    "Programmierer",
    "Projektmanager",
    "Rechtsanwalt",
    "Reinigungskraft",
    "Requisiteur",
    "Richter",
    "Sanitäter",
    "Schauspieler",
    "Schlosser",
    "Schneider",
    "Schornsteinfeger",
    "Schuhmacher",
    "Schweißer",
    "Security",
    "Sekretär",
    "Sozialarbeiter",
    "Soldat",
    "Steuerberater",
    "Straßenbauer",
    "Taxifahrer",
    "Tänzer",
    "Tierarzt",
    "Tierpfleger",
    "Tischler",
    "Trainer",
    "Technischer Zeichner",
    "Uhrmacher",
    "Verkäufer",
    "Webentwickler",
    "Winzer",
    "Wissenschaftler",
    "Zahnarzt",
    "Zimmermann",
    "Zoowärter",
  ],
  orte: [
    "Altstadt",
    "Amsterdam",
    "Aussichtsplattform",
    "Bangkok",
    "Bibliothek",
    "Berlin",
    "Berg",
    "Botanischer Garten",
    "Brüssel",
    "Burg",
    "Café",
    "Chicago",
    "Dubai",
    "Dünen",
    "Einkaufszentrum",
    "Felsen",
    "Flughafen",
    "Fluss",
    "Flussdelta",
    "Flussmündung",
    "Freizeitpark",
    "Fußgängerzone",
    "Gletscher",
    "Gipfel",
    "Hafen",
    "Helsinki",
    "Höhle",
    "Höhenweg",
    "Hügel",
    "Insel",
    "Istanbul",
    "Kapstadt",
    "Kairo",
    "Kanäle",
    "Kathedrale",
    "Kirche",
    "Kliff",
    "Kloster",
    "Kino",
    "Kunstgalerie",
    "Leuchtturm",
    "London",
    "Los Angeles",
    "Madrid",
    "Marktplatz",
    "Marina",
    "Museum",
    "Melbourne",
    "Moskau",
    "Moschee",
    "New York",
    "Nationalpark",
    "Naturpark",
    "Oslo",
    "Park",
    "Peking",
    "Platz",
    "Prag",
    "Promenade",
    "Regenwald",
    "Restaurant",
    "Rummelplatz",
    "Ruine",
    "Schloss",
    "Schlucht",
    "Seilbahn",
    "See",
    "Seeufer",
    "Singapur",
    "Skigebiet",
    "Sportplatz",
    "Stadion",
    "Stadtzentrum",
    "Stockholm",
    "Strand",
    "Strandpromenade",
    "Steppe",
    "Synagoge",
    "Tempel",
    "Theater",
    "Therme",
    "Tundra",
    "Toronto",
    "Vulkan",
    "Wald",
    "Wasserfall",
    "Wüste",
    "Wildpark",
    "Zoo",
    "Zürich",
  ],
  gegenstaende: [
    "Abfalleimer",
    "Abziehbild",
    "Aktenkoffer",
    "Aktenmappe",
    "Aluminiumdose",
    "Aquarium",
    "Aquarellfarben",
    "Aufbewahrungsbox",
    "Armbanduhr",
    "Bibliothek",
    "Bild",
    "Bilderrahmen",
    "Bibel",
    "Blumentopf",
    "Blumenvase",
    "Brille",
    "Brieftasche",
    "Bügeleisen",
    "Bürostuhl",
    "Buch",
    "CD",
    "CD-Regal",
    "Computer",
    "Decke",
    "Dose",
    "Drucker",
    "Einkaufskorb",
    "Eiswürfelform",
    "Etagere",
    "Erste-Hilfe-Kasten",
    "Fernbedienung",
    "Fernseher",
    "Fieberthermometer",
    "Flasche",
    "Fußmatte",
    "Futon",
    "Gabel",
    "Glas",
    "Glasuntersetzer",
    "Garderobe",
    "Gewürzregal",
    "Grill",
    "Haarbürste",
    "Hefter",
    "Hängelampe",
    "Hocker",
    "Hut",
    "Handtuch",
    "Hängematte",
    "Holzregal",
    "Kalender",
    "Kaffeemaschine",
    "Kanne",
    "Karton",
    "Kissen",
    "Klappstuhl",
    "Kerze",
    "Kochbuch",
    "Kochlöffel",
    "Kochplatte",
    "Küchenmaschine",
    "Küchenrolle",
    "Küchenschrank",
    "Koffer",
    "Kreidetafel",
    "Kronleuchter",
    "Kühlschrank",
    "Lampe",
    "Leinwand",
    "Leselampe",
    "Ledertasche",
    "Ledersofa",
    "Lineal",
    "Löffel",
    "Lufterfrischer",
    "Laptop",
    "Messer",
    "Messerblock",
    "Mikrowelle",
    "Mixer",
    "Monitor",
    "Nachttisch",
    "Notizbuch",
    "Notebook",
    "Obstkiste",
    "Ordner",
    "Papier",
    "Papierblock",
    "Papierkorb",
    "Papiertaschentuch",
    "Park",
    "Pfanne",
    "Platzdeckchen",
    "Radiergummi",
    "Rucksack",
    "Regal",
    "Regenschirm",
    "Reinigungsmittel",
    "Ring",
    "Rollcontainer",
    "Roller",
    "Schlafsack",
    "Schlüssel",
    "Schere",
    "Schreibtisch",
    "Schreibtischlampe",
    "Schreibtischstuhl",
    "Schrank",
    "Schublade",
    "Schuhregal",
    "Schüssel",
    "Seife",
    "Seifenspender",
    "Servierplatte",
    "Serviette",
    "Spiegel",
    "Spielzeug",
    "Spüle",
    "Standleuchte",
    "Standuhr",
    "Stehlampe",
    "Steckdose",
    "Stoffbeutel",
    "Stofftier",
    "Stuhl",
    "Ständer",
    "Streuer",
    "Sofa",
    "Teekanne",
    "Tagesdecke",
    "Tasse",
    "Taschenuhr",
    "Tasche",
    "Taschenrechner",
    "Teppich",
    "Teller",
    "Telefon",
    "Thermoskanne",
    "Toaster",
    "Toilettenpapier",
    "Topf",
    "Topflappen",
    "Treppengeländer",
    "Uhr",
    "Unterlage",
    "Vase",
    "Ventilator",
    "Wandlampe",
    "Wandregal",
    "Wasserkocher",
    "Waschbecken",
    "Waschmaschine",
    "Werkzeugkasten",
    "Wohnzimmerlampe",
    "Zahnbürste",
    "Zahnpasta",
    "Zettelblock",
    "Zitronenpresse",
  ],
  lebensmittel: [
    "Agave",
    "Ahornsirup",
    "Amaranth",
    "Ananas",
    "Aubergine",
    "Apfel",
    "Artischocke",
    "Avocado",
    "Baguette",
    "Banane",
    "Beeren",
    "Birne",
    "Blattsalat",
    "Blumenkohl",
    "Bohnen",
    "Bonbon",
    "Brokkoli",
    "Brot",
    "Brötchen",
    "Burger",
    "Champignon",
    "Chili",
    "Couscous",
    "Croissant",
    "Dattel",
    "Dill",
    "Edamame",
    "Ei",
    "Eis",
    "Eisbergsalat",
    "Erdbeere",
    "Feige",
    "Feta",
    "Frischkäse",
    "Frühlingszwiebel",
    "Gnocchi",
    "Garnele",
    "Gurke",
    "Grünkohl",
    "Hähnchen",
    "Himbeere",
    "Himbeerjoghurt",
    "Hirse",
    "Honig",
    "Ingwer",
    "Ingwerwurzel",
    "Joghurt",
    "Joghurtgetränk",
    "Johannisbeere",
    "Kakao",
    "Karotte",
    "Kartoffel",
    "Keks",
    "Kichererbse",
    "Kirsche",
    "Kiwi",
    "Kohl",
    "Kohlrabi",
    "Kokosnuss",
    "Kokosöl",
    "Knäckebrot",
    "Knoblauch",
    "Kürbis",
    "Kürbiskerne",
    "Lachs",
    "Lasagne",
    "Leinsamen",
    "Linsen",
    "Linsensuppe",
    "Maisschote",
    "Maismehl",
    "Mandeln",
    "Mandarine",
    "Mango",
    "Melone",
    "Milch",
    "Minze",
    "Minztee",
    "Pancake",
    "Papaya",
    "Paprika",
    "Pasta",
    "Pastinake",
    "Pfirsich",
    "Pflaume",
    "Pecannuss",
    "Pizza",
    "Pudding",
    "Pinienkerne",
    "Quark",
    "Quinoa",
    "Radieschen",
    "Räucherlachs",
    "Reis",
    "Rhabarber",
    "Roggenbrot",
    "Rosinen",
    "Rote Bete",
    "Rucola",
    "Sahne",
    "Salami",
    "Salat",
    "Sellerie",
    "Sauerrahm",
    "Schokolade",
    "Schnitzel",
    "Sesam",
    "Shrimps",
    "Sojasauce",
    "Sojamilch",
    "Speck",
    "Spaghetti",
    "Spinat",
    "Steak",
    "Steinpilz",
    "Streusel",
    "Tofu",
    "Toffifee",
    "Tomate",
    "Torte",
    "Traube",
    "Thunfisch",
    "Trüffel",
    "Vanille",
    "Vanilleeis",
    "Waffel",
    "Walnuss",
    "Wassermelone",
    "Wurst",
    "Weizenmehl",
    "Zimt",
    "Zitrone",
    "Zitronensaft",
    "Zucchini",
    "Zucker",
    "Zuckerrübe",
    "Zuckerguss",
    "Zwetschge",
    "Zwiebel",
  ],
  verben: [
    "abholen",
    "abschalten",
    "abschließen",
    "abwaschen",
    "arbeiten",
    "aufbauen",
    "aufhören",
    "aufmachen",
    "aufräumen",
    "aufstehen",
    "ausatmen",
    "ausfüllen",
    "ausleihen",
    "auspacken",
    "ausruhen",
    "aussehen",
    "backen",
    "baden",
    "beginnen",
    "beenden",
    "behandeln",
    "bekommen",
    "beobachten",
    "besuchen",
    "bezahlen",
    "biegen",
    "binden",
    "blättern",
    "brechen",
    "bringen",
    "denken",
    "diskutieren",
    "duschen",
    "drücken",
    "einkaufen",
    "einladen",
    "einpacken",
    "einschalten",
    "einsteigen",
    "einziehen",
    "essen",
    "erfahren",
    "erklären",
    "erlauben",
    "erleben",
    "erreichen",
    "erinnern",
    "erschrecken",
    "erwarten",
    "erzählen",
    "fangen",
    "feiern",
    "finden",
    "folgen",
    "fragen",
    "geben",
    "gewinnen",
    "glauben",
    "gratulieren",
    "halten",
    "haben",
    "hassen",
    "heiraten",
    "helfen",
    "hören",
    "hoffen",
    "kochen",
    "kaufen",
    "kämpfen",
    "klettern",
    "kommen",
    "kosten",
    "kreieren",
    "küssen",
    "laufen",
    "leihen",
    "lernen",
    "lesen",
    "liegen",
    "lieben",
    "malen",
    "meiden",
    "mieten",
    "mitarbeiten",
    "mitbringen",
    "mitkommen",
    "mögen",
    "nehmen",
    "öffnen",
    "organisieren",
    "packen",
    "planen",
    "putzen",
    "reisen",
    "reden",
    "rennen",
    "retten",
    "rufen",
    "sagen",
    "sammeln",
    "schalten",
    "schauen",
    "scheinen",
    "schicken",
    "schließen",
    "schlafen",
    "schleppen",
    "schmecken",
    "schneiden",
    "schreiben",
    "schreien",
    "schwimmen",
    "sehen",
    "sein",
    "senden",
    "singen",
    "sitzen",
    "sparen",
    "spielen",
    "suchen",
    "sprechen",
    "springen",
    "stärken",
    "stellen",
    "studieren",
    "tanzen",
    "trinken",
    "trennen",
    "träumen",
    "überarbeiten",
    "überlegen",
    "übernehmen",
    "überraschen",
    "überprüfen",
    "überzeugen",
    "überweisen",
    "umarmen",
    "umfahren",
    "umziehen",
    "unterbrechen",
    "unterhalten",
    "unterrichten",
    "unterstützen",
    "verändern",
    "vergessen",
    "verkaufen",
    "vergleichen",
    "verlassen",
    "vermeiden",
    "vermieten",
    "verpassen",
    "verschenken",
    "verstehen",
    "verzögern",
    "vorbereiten",
    "vorlesen",
    "vorstellen",
    "warten",
    "waschen",
    "weinen",
    "wenden",
    "werfen",
    "wiederholen",
    "wünschen",
    "zeigen",
    "ziehen",
    "zuhören",
    "zurückgeben",
    "zusammenarbeiten",
    "zusammenbauen",
    "zusammenfassen",
    "zusammenhalten",
    "zusammenkommen",
    "zweifeln",
  ],
  adjektive: [
    "alt",
    "arm",
    "ärgerlich",
    "ängstlich",
    "aufgeregt",
    "auffällig",
    "ausgeglichen",
    "bald",
    "bitter",
    "blass",
    "blau",
    "breit",
    "bunt",
    "dankbar",
    "dick",
    "digital",
    "dumm",
    "dunkel",
    "eifersüchtig",
    "einfach",
    "einzigartig",
    "eklig",
    "eng",
    "erfolgreich",
    "erschöpft",
    "etwas",
    "faul",
    "falsch",
    "farbenfroh",
    "fett",
    "fleißig",
    "freundlich",
    "frisch",
    "fröhlich",
    "frei",
    "gefährlich",
    "gelb",
    "gerade",
    "gesund",
    "gestresst",
    "glatt",
    "glücklich",
    "grob",
    "groß",
    "großartig",
    "gut",
    "hart",
    "heiß",
    "hell",
    "hilfreich",
    "hohl",
    "hübsch",
    "hungrig",
    "interessant",
    "jung",
    "kaputt",
    "klangvoll",
    "klar",
    "klein",
    "klug",
    "komisch",
    "kompliziert",
    "kreativ",
    "kühl",
    "kurz",
    "laut",
    "lebendig",
    "leicht",
    "lieb",
    "liebenswürdig",
    "locker",
    "lustig",
    "luxuriös",
    "malerisch",
    "mangelhaft",
    "mutig",
    "nah",
    "nass",
    "neu",
    "normal",
    "notwendig",
    "offen",
    "optimal",
    "orange",
    "ordentlich",
    "praktisch",
    "preiswert",
    "pünktlich",
    "rasiert",
    "reich",
    "rot",
    "ruhig",
    "runter",
    "rund",
    "sauer",
    "scharf",
    "schattig",
    "schlau",
    "schmal",
    "schmutzig",
    "schnell",
    "schön",
    "schrecklich",
    "schwach",
    "schwer",
    "selten",
    "selbstständig",
    "seriös",
    "sicher",
    "simples",
    "skurril",
    "sorgfältig",
    "schnuckelig",
    "spannend",
    "sportlich",
    "stark",
    "still",
    "stilvoll",
    "stolz",
    "strukturiert",
    "stürmisch",
    "süß",
    "teuer",
    "tief",
    "toll",
    "trocken",
    "typisch",
    "überraschend",
    "unabhängig",
    "unbekannt",
    "ungeduldig",
    "unglaublich",
    "unangenehm",
    "unheimlich",
    "uninteressant",
    "unsicher",
    "unsichtbar",
    "unterhaltsam",
    "unverzichtbar",
    "viele",
    "vielleicht",
    "voll",
    "vorhersehbar",
    "vorsichtig",
    "warm",
    "weich",
    "weit",
    "wertvoll",
    "wichtig",
    "widerlich",
    "wild",
    "wirklich",
    "wohlhabend",
    "wunderbar",
    "wütend",
    "zahm",
    "zeitlos",
    "zeitnah",
    "zentral",
    "zickig",
    "zielstrebig",
    "zufrieden",
    "zugänglich",
    "zugeschnitten",
    "zukunftsorientiert",
    "zuverlässig",
    "zuvorkommend",
    "zwanglos",
    "zwielichtig",
  ],
  sport: [
    "Aerobic",
    "Aikido",
    "Akrobatik",
    "American Football",
    "Angeln",
    "Badminton",
    "Baseball",
    "Basketball",
    "Beachvolleyball",
    "Bergsteigen",
    "Billard",
    "Biathlon",
    "Bob fahren",
    "Bogenschießen",
    "Boxen",
    "Bowling",
    "Breakdance",
    "Capoeira",
    "Cheerleading",
    "Cricket",
    "Crossfit",
    "Darts",
    "Eishockey",
    "Feldhockey",
    "Fallschirmspringen",
    "Fechten",
    "Fußball",
    "Freestyle-Ski",
    "Gleitschirmfliegen",
    "Gewichtheben",
    "Golf",
    "Gymnastik",
    "Hip Hop",
    "Handball",
    "Inline-Skaten",
    "Jiu-Jitsu",
    "Judo",
    "Karate",
    "Kajak",
    "Kartrennen",
    "Kickboxen",
    "Klettern",
    "Kitesurfen",
    "Kunstturnen",
    "Langlauf",
    "Laufen",
    "Leichtathletik",
    "Marathon",
    "Motocross",
    "Mountainbike",
    "Moderner Fünfkampf",
    "Nordic Walking",
    "Orientierungslauf",
    "Paddeln",
    "Parkour",
    "Pilates",
    "Polo",
    "Radsport",
    "Rallyesport",
    "Reiten",
    "Ringen",
    "Rodeln",
    "Rudern",
    "Rugby",
    "Schach",
    "Schießen",
    "Schlittschuhlaufen",
    "Schneeschuhwandern",
    "Schwimmen",
    "Segeln",
    "Skateboarden",
    "Skifahren",
    "Skispringen",
    "Slacklining",
    "Snowboarden",
    "Snooker",
    "Speerwurf",
    "Squash",
    "Stand-Up-Paddling",
    "Surfen",
    "Taekwondo",
    "Tanzen",
    "Tennis",
    "Tischtennis",
    "Triathlon",
    "Trampolin",
    "Turnen",
    "Ultimate Frisbee",
    "Volleyball",
    "Wakeboarden",
    "Wandern",
    "Wasserski",
    "Windsurfen",
    "Wrestling",
    "Yoga",
    "Zumba",
  ],
}

const categoryLabels: Record<string, string> = {
  tiere: "Tiere",
  berufe: "Berufe",
  orte: "Orte",
  gegenstaende: "Gegenstände",
  lebensmittel: "Lebensmittel",
  verben: "Verben (Aktivitäten)",
  adjektive: "Adjektive (Eigenschaften)",
  sport: "Sport & Aktivitäten",
}

export default function WortGeneratorPage() {
  const [category, setCategory] = useState<string>("tiere")
  const [currentWord, setCurrentWord] = useState<string | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [history, setHistory] = useState<{ word: string; category: string }[]>([])
  const [isExpanded, setIsExpanded] = useState(false)

  const generateWord = () => {
    setIsGenerating(true)

    let count = 0
    const interval = setInterval(() => {
      const words = wordCategories[category]
      const randomWord = words[Math.floor(Math.random() * words.length)]
      setCurrentWord(randomWord)
      count++

      if (count >= 10) {
        clearInterval(interval)
        const finalWord = words[Math.floor(Math.random() * words.length)]
        setCurrentWord(finalWord)
        setHistory((prev) => [{ word: finalWord, category: categoryLabels[category] }, ...prev.slice(0, 19)])
        setIsGenerating(false)
      }
    }, 100)
  }

  const clearHistory = () => {
    setHistory([])
  }

  if (isExpanded) {
    return (
      <div className="fixed inset-0 z-50 bg-gradient-to-b from-gray-900 to-gray-800 flex flex-col">
        <div className="flex justify-between items-center p-4">
          <div className="flex items-center gap-3">
            <MessageSquareText className="w-8 h-8 text-pink-400" />
            <span className="text-white font-bold text-xl">Wort-Generator</span>
          </div>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => setIsExpanded(false)}
            className="text-white hover:bg-white/10"
          >
            <X className="w-5 h-5" />
          </Button>
        </div>

        <div className="flex-1 flex flex-col items-center justify-center gap-8 p-4">
          <div className="text-center py-12 px-16 rounded-3xl bg-white/10 w-[500px] h-[300px] flex items-center justify-center">
            <AnimatePresence mode="wait">
              {currentWord ? (
                <motion.div
                  key={currentWord}
                  initial={{ scale: 0.5, opacity: 0 }}
                  animate={{ scale: 1, opacity: 1 }}
                  exit={{ scale: 0.5, opacity: 0 }}
                  className={`text-6xl font-bold ${isGenerating ? "text-gray-500" : "text-pink-400"} break-words`}
                >
                  {currentWord}
                </motion.div>
              ) : (
                <span className="text-gray-400 text-xl">Tippe auf Wort generieren</span>
              )}
            </AnimatePresence>
          </div>

          <Button
            onClick={generateWord}
            disabled={isGenerating}
            size="lg"
            className="h-14 px-12 text-lg bg-pink-500 hover:bg-pink-600"
          >
            <RefreshCw className={`w-5 h-5 mr-3 ${isGenerating ? "animate-spin" : ""}`} />
            {isGenerating ? "Generiere..." : "Wort generieren"}
          </Button>
        </div>

        <div className="p-4 flex justify-center">
          <Select
            value={category}
            onValueChange={(val) => {
              setCategory(val)
              setCurrentWord(null)
            }}
          >
            <SelectTrigger className="w-48 h-10 bg-white/10 border-white/20 text-white">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              {Object.entries(categoryLabels).map(([key, label]) => (
                <SelectItem key={key} value={key}>
                  {label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen flex flex-col bg-gradient-to-b from-gray-50 to-white">
      <Navigation />
      <main className="flex-1 container mx-auto px-4 py-8">
        <Link
          href="/spielhilfen"
          className="inline-flex items-center gap-2 text-gray-600 hover:text-teal-600 mb-6 transition-colors"
        >
          <ArrowLeft className="w-4 h-4" />
          <span className="text-sm">Zurück zur Übersicht</span>
        </Link>

        <Card className="max-w-2xl mx-auto border-2 border-gray-200">
          <CardHeader className="text-center border-b bg-gradient-to-r from-pink-50 to-pink-100">
            <motion.div
              animate={{ rotate: [0, 10, -10, 0] }}
              transition={{ duration: 2, repeat: Number.POSITIVE_INFINITY, ease: "easeInOut" }}
              className="w-14 h-14 rounded-xl bg-pink-500 flex items-center justify-center mx-auto mb-2 shadow-lg"
            >
              <MessageSquareText className="w-8 h-8 text-white" />
            </motion.div>
            <CardTitle className="text-2xl">Wort-Generator</CardTitle>
            <p className="text-gray-500 text-sm">Zufällige Wörter für Wortspiele</p>
          </CardHeader>
          <CardContent className="p-4 space-y-4">
            <div>
              <label className="mb-1 block font-bold text-sm text-foreground">Kategorie</label>
              <Select
                value={category}
                onValueChange={(val) => {
                  setCategory(val)
                  setCurrentWord(null)
                  setHistory([])
                }}
              >
                <SelectTrigger className="w-full h-8 text-xs">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {Object.entries(categoryLabels).map(([key, label]) => (
                    <SelectItem key={key} value={key}>
                      {label}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>

            <div className="relative">
              <Button
                variant="ghost"
                size="sm"
                onClick={() => setIsExpanded(true)}
                className="absolute top-2 right-2 h-6 w-6 p-0 text-gray-400 hover:text-gray-600 hover:bg-gray-100 z-10"
                title="Vergrössern"
              >
                <Maximize2 className="w-3.5 h-3.5" />
              </Button>
              <div className="bg-gray-50 rounded-xl p-6 text-center h-[180px] flex items-center justify-center border-2 border-gray-200">
                <AnimatePresence mode="wait">
                  {currentWord ? (
                    <motion.div
                      key={currentWord}
                      initial={{ scale: 0.5, opacity: 0 }}
                      animate={{ scale: 1, opacity: 1 }}
                      exit={{ scale: 0.5, opacity: 0 }}
                      className={`text-3xl font-bold ${isGenerating ? "text-gray-400" : "text-pink-600"} break-words`}
                    >
                      {currentWord}
                    </motion.div>
                  ) : (
                    <span className="text-gray-400 text-xs">Klicke auf "Wort generieren"</span>
                  )}
                </AnimatePresence>
              </div>
            </div>

            <Button
              onClick={generateWord}
              disabled={isGenerating}
              className="w-full h-8 text-sm bg-pink-500 hover:bg-pink-600"
            >
              <RefreshCw className={`w-3 h-3 mr-2 ${isGenerating ? "animate-spin" : ""}`} />
              {isGenerating ? "Generiere..." : "Wort generieren"}
            </Button>

            {history.length > 0 && (
              <div className="border-t pt-3">
                <div className="flex items-center justify-between mb-2">
                  <span className="text-gray-700 text-sm font-bold">Verlauf</span>
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={clearHistory}
                    className="text-gray-400 hover:text-gray-600 h-6 w-6 p-0"
                  >
                    <Trash2 className="w-3 h-3" />
                  </Button>
                </div>
                <div className="space-y-1 max-h-40 overflow-y-auto">
                  {history.map((item, i) => (
                    <div key={i} className="flex items-center justify-between text-xs bg-gray-50 p-1.5 rounded">
                      <span className="font-medium text-gray-800">{item.word}</span>
                      <span className="text-xs text-gray-500 bg-gray-200 px-1.5 py-0.5 rounded">{item.category}</span>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      </main>
    </div>
  )
}
